name: spyder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - spyder-kernels=3.*
  - spyder
  - cython
  - scipy
  - pandas
  - sympy
  - matplotlib
  - numpy
  - conda-lock
  - git